-- Returns a read-only menu entry function; supplied configuration is generated by the installer.
return function(options)
 local report_dir=assert(options.reports)
 local stamp=os.date('%Y%m%d-%H%M%S')
 local base=report_dir..'/audit-'..stamp
 local function exists(p) local f=io.open(p,'rb');if f then f:close();return true end;return false end
 local n=0;while exists(base..'.json') or exists(base..'.log') do n=n+1;base=report_dir..'/audit-'..stamp..'-'..n end
 local log=assert(io.open(base..'.log','w'))
 local ok,result=xpcall(function()
  if not resolve then
   for _,o in pairs({app=app,fusion=fusion}) do
    local yes,r=pcall(function()return o:GetResolve()end)
    if yes and r then resolve=r;break end
   end
  end
  assert(resolve,'No in-process Resolve object')
  local p=assert(resolve:GetProjectManager():GetCurrentProject(),'No current project')
  assert(p:GetName()==options.expected_project,'Project mismatch; no audit performed')
  local result=dofile(options.root..'/skills/edit-davinci-video/scripts/inspect_resolve.lua')({expected_project=options.expected_project,output_path=base..'.json'})
  local f=assert(io.open(base..'-renders.txt','w'))
  f:write('RenderingInProgress=',tostring(p:IsRenderingInProgress()),'\n')
  for _,job in ipairs(p:GetRenderJobList() or {}) do
   f:write('JobId=',tostring(job.JobId),'\n')
   for k,v in pairs(p:GetRenderJobStatus(job.JobId) or {}) do f:write(tostring(k),'=',tostring(v),'\n') end
  end
  f:close();return result
 end,debug.traceback)
 log:write('success=',tostring(ok),'\n',tostring(result),'\n');log:close()
 print('CODEX_READ_ONLY_AUDIT',ok,base);assert(ok,result);return base
end
